CREATE DATABASE k11
USE k11


CREATE TABLE users (
	`id` INT AUTO_INCREMENT PRIMARY KEY,	
	`name` VARCHAR(250) NOT NULL,
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`password` VARCHAR(250) NOT NULL,
	`created at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paket(
	`Tag` INT PRIMARY KEY,
	`Nama` VARCHAR(100) NOT NULL,
	`Tanggal Kedatangan` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`Pengirim` VARCHAR(100) NOT NULL,
	`Deskripsi` VARCHAR(100) NOT NULL,
	`Status Paket` VARCHAR(50) NOT NULL
);

SELECT* FROM users
SELECT * FROM paket

DROP TABLE paket
DROP TABLE users