/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import controllers.PaketController;
import controllers.UserController;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.DaftarPaket;
import models.User;
import utils.DatabaseUtil;

/**
 *
 * @author USER
 */
public class TambahPaket extends javax.swing.JFrame {

    DatabaseUtil koneksi = new DatabaseUtil();
    ResultSet rs;
    PreparedStatement pre;
    
    public TambahPaket() {
        setIcon();
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTag = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPengirim = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        btnTambahPaket = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setText("Tambah Paket");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 190, 30));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Tag");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Pengirim");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Deskripsi Paket");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtTag.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txtTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 290, 30));

        txtNama.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, 30));

        txtPengirim.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txtPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 290, 30));

        txtDeskripsi.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeskripsiActionPerformed(evt);
            }
        });
        txtDeskripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeskripsiKeyPressed(evt);
            }
        });
        jPanel1.add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 290, 30));

        btnTambahPaket.setBackground(new java.awt.Color(51, 204, 0));
        btnTambahPaket.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnTambahPaket.setText("Tambahkan Paket");
        btnTambahPaket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambahPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPaketActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 380, 150, 50));

        btnBatalTambah.setBackground(new java.awt.Color(255, 0, 0));
        btnBatalTambah.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBatalTambah.setText("Batal");
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 180, 50));

        cmbStatus.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum diambil", "Sudah diambil" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 160, 30));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Status Paket");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/tambahpaket.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        Background.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/BGBeranda1.jpg"))); // NOI18N
        Background.setText("jLabel1");
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        // TODO add your handling code here:
        MyDaftarPaket2 jb2 = new MyDaftarPaket2();
        jb2.show();
        
        dispose(); //Nutup si MyDaftarPaket
    }//GEN-LAST:event_btnBatalTambahActionPerformed
PaketController pc = new PaketController();
    private void btnTambahPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPaketActionPerformed
        String Status = (String) cmbStatus.getSelectedItem();
        String tempTag = "";  
        
        String cek = "SELECT * FROM paket WHERE Tag=" + txtTag.getText();
        
        
        try {
            rs = koneksi.executeSelect(cek);
            while(rs.next()){
                tempTag = rs.getString(1);
            } 
        } catch (SQLException ex) {
            Logger.getLogger(TambahPaket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(tempTag.equals(txtTag.getText())) {
            JOptionPane.showMessageDialog(null, "Tag yang diinput sudah terpakai", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);

        } else if(txtTag.getText().isBlank() || txtNama.getText().isBlank() || txtPengirim.getText().isBlank() || txtDeskripsi.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Tidak boleh ada data yang kosong.",
                                   "ERROR", JOptionPane.ERROR_MESSAGE); return;
        } else {
            String query = "INSERT INTO paket(Tag, `Nama`, `Pengirim`, `Deskripsi`, `Status Paket`)VALUES(\""
                  + txtTag.getText() + "\",\""
                  + txtNama.getText() + "\",\""
                  + txtPengirim.getText() + "\",\""
                  + txtDeskripsi.getText() + "\",\""
                  + Status
                  + "\")";
          
            DaftarPaket pkt = new DaftarPaket(txtTag.getText(), txtNama.getText(), txtPengirim.getText(), txtDeskripsi.getText(), null, Status);
            if(pc.insert(pkt)){

                new MyDaftarPaket2().setVisible(true);
                this.dispose();
            }
            else{
                      JOptionPane.showMessageDialog(this, "Gagal menambahkan paket! \nMasukkan data yang sesuai",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        

        }
        
//        MyDaftarPaket2 jb2 = new MyDaftarPaket2();
//        jb2.show();
//        
//        dispose();
    }//GEN-LAST:event_btnTambahPaketActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void txtDeskripsiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeskripsiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String Status = (String) cmbStatus.getSelectedItem();
        String tempTag = "";  
        
        String cek = "SELECT * FROM paket WHERE Tag=" + txtTag.getText();
        
        
        try {
            rs = koneksi.executeSelect(cek);
            while(rs.next()){
                tempTag = rs.getString(1);
            } 
        } catch (SQLException ex) {
            Logger.getLogger(TambahPaket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(tempTag.equals(txtTag.getText())) {
            JOptionPane.showMessageDialog(null, "Tag yang diinput sudah terpakai", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);

        } else if(txtTag.getText().isBlank() || txtNama.getText().isBlank() || txtPengirim.getText().isBlank() || txtDeskripsi.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Tidak boleh ada data yang kosong.",
                                   "ERROR", JOptionPane.ERROR_MESSAGE); return;
        } else {
            String query = "INSERT INTO paket(Tag, `Nama`, `Pengirim`, `Deskripsi`, `Status Paket`)VALUES(\""
                  + txtTag.getText() + "\",\""
                  + txtNama.getText() + "\",\""
                  + txtPengirim.getText() + "\",\""
                  + txtDeskripsi.getText() + "\",\""
                  + Status
                  + "\")";
        
//          koneksi.execute(query);
          
            DaftarPaket pkt = new DaftarPaket(txtTag.getText(), txtNama.getText(), txtPengirim.getText(), txtDeskripsi.getText(), null, Status);
            if(pc.insert(pkt)){

                new MyDaftarPaket2().setVisible(true);
                this.dispose();
            }
            else{
                      JOptionPane.showMessageDialog(this, "Gagal menambahkan paket! \nMasukkan data yang sesuai",
                                       "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        

        }
        }
    }//GEN-LAST:event_txtDeskripsiKeyPressed

    private void txtDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeskripsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnTambahPaket;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPengirim;
    private javax.swing.JTextField txtTag;
    // End of variables declaration//GEN-END:variables
private void setIcon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Flimenabig.png")));
}



}
